// src/app/shered/component/back-arrow/back-arrow.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

import { iconPatch } from '../../../core/constant/icons';

@Component({
  selector: 'app-back-arrow',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './back-arrow.component.html',
  styleUrl: './back-arrow.component.css'
})
export class BackArrowComponent {

@Input() path?:string

icon = iconPatch.backArrow

}

<a [routerLink]="path">
    <svg viewBox="0 0 30 30" class="iconBack">
        <path [attr.d]="icon" fill="#FFFFFF"></path>
    </svg>
</a>

// src/components/BackArrow/BackArrow.jsx
import { Link } from "react-router-dom";
import icons from "../../const/icons"
import styles from "./BackArrow.module.css"

const BackArrow = ({path}) =>{
    
    return(
        <Link className={styles.iconBack} to={path}>   
            <svg viewBox="0 0 30 30">
                <path d={icons.backArrow} fill="#FFFFFF"></path>
            </svg>
        </Link>
    );
}

export default BackArrow;
