// src/app/shered/component/form-field/form-field.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-form-field',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './form-field.component.html',
  styleUrl: './form-field.component.css'
})
export class FormFieldComponent {

  @Input() iconPatch?:string;
  @Input() type:string="text";
  @Input() name?:string;
  @Input() placeholder?:string;
  @Input() inputmode?:string;
  @Input() viewBox:string='0 0 16 16';
  @Input() formControlName?:string;
  @Input() pattern?:string;
  @Input() errorMessage?:string;
  
  @Output() form = new EventEmitter<any>();

  sendValueUp(event:any){
    if(!this.pattern){
      this.form.emit(event);
      return
    }

    const regex = new RegExp(this.pattern)
    const inputValue = event.target.value;

    if(regex.test(event.target.value)){
        this.form.emit(event);
      return
    }
    event.target.value = inputValue.slice(0,-1)
  }
}

<div class="field">
    <svg class="inputIcon" width="16" height="16" fill="currentColor" [attr.viewBox]="viewBox">
        <path [attr.d]="iconPatch"></path>
    </svg>
    <input
        class="inputField"
        [type]="type"
        [name]="name"
        [placeholder]="placeholder"
        [inputMode]="inputmode"
        [attr.formControlName]="formControlName"
        (input)="sendValueUp($event)"
    />
</div>
@if (errorMessage){
    <p class="errorMessage">{{errorMessage}}</p>
}

// src/components/FormField/FormField.jsx
import styles from "./FormField.module.css"

const FormField = (props) => {
    const {iconPatch, onChange, type, name, placeholder,pattern, inputMode, viewBox = "0 0 16 16"} = props;
    const regex = new RegExp(pattern)
    
    const handleChange = (event) =>{
        const inputValue = event.target.value;

        if(regex.test(inputValue)){
            onChange(event)
            return
        }
        event.target.value = inputValue.slice(0,-1)
    };
    
    return(
        <div className={styles.field}>
            <svg className={styles.inputIcon} width="16" height="16" fill="currentColor" viewBox={viewBox}>
                <path d={iconPatch}></path>
            </svg>
            <input 
                onChange={(event) => handleChange(event)}
                placeholder={placeholder}
                className={styles.inputField}
                type={type}
                name={name}
                inputMode={inputMode}
            />
        </div>
    );
};

export default FormField
