// src/app/core/pages/home-page/home-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterLink } from '@angular/router';

import { iconPatch } from '../../constant/icons';

import { Auth } from '../../services/auth/auth';

@Component({
  selector: 'app-home-page',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './home-page.component.html',
  styleUrl: './home-page.component.css'
})
export class HomePageComponent implements OnInit{

  icons = iconPatch


  constructor(
    private auth:Auth,
    private router:Router
  ){}

  ngOnInit(){
    this.auth.checkToken();
  }

  public navigate(event:any){
    let id:string = event.target.id;
    setTimeout(()=>{
      switch(id){
        case "aquarium":
          this.router.navigate(['/aquarium/all/']);
          break;
        case "lamps":
          this.router.navigate(['/lamps/all/']);
          break;
      }
    },500)
  }

}

<nav class="container">

    <a [routerLink]="[ '' ]">
        <svg viewBox="0 0 30 30" class="containerIcon settingsIcon">
            <path [attr.d]="icons.settings" fill="#FFFFFF"></path>
        </svg>
    </a>
    <a [routerLink]="[ '/add/device' ]">
        <svg viewBox="0 0 30 30" class="containerIcon addIcon">
            <path [attr.d]="icons.plus" fill="#FFFFFF"></path>
        </svg>
    </a>

    <button class="container_button" id="aquarium" (click)="navigate($event)" > Akwarium </button>
    <button class="container_button" id="lamps" (click)="navigate($event)"> Lampy </button>
</nav>

// src/pages/HomePage/HomePage.jsx
import icons from "../../const/icons"

import { Link ,useNavigate} from "react-router-dom";
import useAuth from "../../hooks/useAuth";
import styles from "./HomePage.module.css"

const HomePage = () =>{
    const {} = useAuth();
    const navigate = useNavigate();

    const nav = (event) =>{
        const PAGE = event.target.id;
        setTimeout(()=>{
            switch(PAGE){
                case "aqua":
                    navigate("/aquarium/all/");
                    break;
                case "stairs":
                    navigate("/",);
                    break;
            }
            
        },500);
    }

    return(
        <div className={styles.container}>
            <Link className={`${ styles.containerIcon} ${styles.settingsIcon}`}>
                <svg viewBox="0 0 30 30">
                    <path d={icons.settings} fill="#FFFFFF"></path>
                </svg>
            </Link>
            <Link className={`${styles.containerIcon} ${styles.addIcon}`} to="/add/device/">
                <svg viewBox="0 0 30 30">
                    <path d={icons.plus} fill="#FFFFFF"></path>
                </svg>
            </Link>
            <button className={styles.containerLink} id="aqua" onClick={nav}>Akwarium</button>
            <button className={styles.containerLink} id="stairs" onClick={nav} >Schody</button>
        </div>
    )
}

export default HomePage
